name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: ./
    #   with:
    #     milliseconds: 1000
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash    
    - run: |
        echo Yo
        echo Wassup
      id: Yo
      shell: bash
    - run: ${{ github.action_path }}/hello.sh
      id: Hello
      shell: bash
    - run: echo random-number ${{ steps.random-number-generator.outputs.random-id }}
      shell: bash          
    - uses: cjineson/javascript-action-test@v2
      with:
        milliseconds: 1000